name: "trigger image build and push to docker hub"
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: upskew/flutter-node:latest
      - name: print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
