name: "trigger image build"
on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: trigger image build
        env:
          BUILD_TRIGGER_ENDPOINT: ${{ secrets.DOCKER_HUB_BUILD_TRIGGER_ENDPOINT }}
        run: |
          curl --silent --show-error --fail -o /dev/null -w "%{http_code}"  -X POST "${BUILD_TRIGGER_ENDPOINT}"
